import processing.core.PApplet;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App extends PApplet{
	private static boolean gameRunning;
	private static boolean targetBlown;
	
    public String getGreeting() {
        return "Don't touch ma spaghet.";
    }

    public void mousePressed() {
        InputHandler.addEvent(new MouseEvent(this, mouseX, mouseY, MouseEvent.Type.PRESS));
    }

    public void mouseReleased() {
        InputHandler.addEvent(new MouseEvent(this, mouseX, mouseY, MouseEvent.Type.RELEASE));
    }

    public void keyPressed() {
        InputHandler.keyDown.put(keyCode, true);
    }

    public void keyReleased() {
        InputHandler.keyDown.put(keyCode, false);
    }

    public void settings() {
        fullScreen();
    }

    public void setup() {
        ellipse(width/2, height/2, height, height);
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    	// Use processing to set frame rate
        gameRunning = true;
        targetBlown = false;
        while (gameRunning) {
        	while (!targetBlown) {
        		
        	}
        }
    }
}
